# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-14 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('twitter', '0002_imagetweet_videotweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
